language: node_js
node_js:
  - "8"
branches:
  only:
    - gulp

branches:
  except:
    - master
    - old
cache:
    directories:
        - "node_modules"

script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./deploy.sh; else npm run build; fi'
